from BaseClasses import Item, ItemClassification

from typing import Dict, NamedTuple, Optional, Set

class VespadianItem(Item):
    game: str = "Vespadian"

class VespadianItemData(NamedTuple):
    category: str
    code: int
    classification: ItemClassification = ItemClassification.filler

def get_items_by_category(category: str) -> Dict[str, VespadianItemData]:
    item_dict: Dict[str, VespadianItemData] = {}
    for name, data in item_table.items():
        if data.category == category:
            item_dict.setdefault(name, data)

    return item_dict

item_table: Dict[str, VespadianItemData] = {
    "Victory":                           VespadianItemData("VIC",              code = 1664, classification = ItemClassification.progression,                  ),
    "Arming Sword":                      VespadianItemData("Equipment",        code = 5, classification = ItemClassification.filler,                       ),
    "Mace":                      VespadianItemData("Equipment",        code = 6, classification = ItemClassification.filler,                       ),
    "Femur":                      VespadianItemData("Equipment",        code = 7, classification = ItemClassification.filler,                       ),
    "Flametongue":                      VespadianItemData("Equipment",        code = 8, classification = ItemClassification.filler,                       ),
    "Longsword":                      VespadianItemData("Equipment",        code = 9, classification = ItemClassification.filler,                       ),
    "Spear":                      VespadianItemData("Equipment",        code = 11, classification = ItemClassification.filler,                       ),
    "Halberd":                      VespadianItemData("Equipment",        code = 12, classification = ItemClassification.filler,                       ),
    "Light Hammer":                      VespadianItemData("Equipment",        code = 13, classification = ItemClassification.filler,                       ),
    "Quarterstaff":                      VespadianItemData("Equipment",        code = 14, classification = ItemClassification.filler,                       ),
    "Battleaxe":                      VespadianItemData("Equipment",        code = 15, classification = ItemClassification.filler,                       ),
    "Greataxe":                      VespadianItemData("Equipment",        code = 16, classification = ItemClassification.filler,                       ),
    "Warhammer":                      VespadianItemData("Equipment",        code = 17, classification = ItemClassification.filler,                       ),
    "Scythe":                      VespadianItemData("Equipment",        code = 18, classification = ItemClassification.filler,                       ),
    "Club":                      VespadianItemData("Equipment",        code = 19, classification = ItemClassification.filler,                       ),
    "Greatclub":                      VespadianItemData("Equipment",        code = 20, classification = ItemClassification.filler,                       ),
    "Staff of Life":                      VespadianItemData("Equipment",        code = 21, classification = ItemClassification.filler,                       ),
    "Staff of Radiance":                      VespadianItemData("Equipment",        code = 22, classification = ItemClassification.filler,                       ),
    "Dream Blade":                      VespadianItemData("Equipment",        code = 23, classification = ItemClassification.filler,                       ),
    "Iron Staff":                      VespadianItemData("Equipment",        code = 24, classification = ItemClassification.filler,                       ),
    "Mythril Sword":                      VespadianItemData("Equipment",        code = 25, classification = ItemClassification.filler,                       ),
    "Mythril Longsword":                      VespadianItemData("Equipment",        code = 26, classification = ItemClassification.filler,                       ),
    "Mythril Battleaxe":                      VespadianItemData("Equipment",        code = 27, classification = ItemClassification.filler,                       ),
    "Mythril Greataxe":                      VespadianItemData("Equipment",        code = 28, classification = ItemClassification.filler,                       ),
    "Mythril Warhammer":                      VespadianItemData("Equipment",        code = 29, classification = ItemClassification.filler,                       ),
    "Mythril Mace":                      VespadianItemData("Equipment",        code = 30, classification = ItemClassification.filler,                       ),
    "Mythril Scythe":                      VespadianItemData("Equipment",        code = 31, classification = ItemClassification.filler,                       ),
    "Mythril Spear":                      VespadianItemData("Equipment",        code = 32, classification = ItemClassification.filler,                       ),
    "Mythril Halberd":                      VespadianItemData("Equipment",        code = 33, classification = ItemClassification.filler,                       ),
    "Orichalcum Sword":                      VespadianItemData("Equipment",        code = 34, classification = ItemClassification.filler,                       ),
    "Orichalcum Longsword":                      VespadianItemData("Equipment",        code = 35, classification = ItemClassification.filler,                       ),
    "Orichalcum Battleaxe":                      VespadianItemData("Equipment",        code = 36, classification = ItemClassification.filler,                       ),
    "Orichalcum Greataxe":                      VespadianItemData("Equipment",        code = 37, classification = ItemClassification.filler,                       ),
    "Orichalcum Warhammer":                      VespadianItemData("Equipment",        code = 38, classification = ItemClassification.filler,                       ),
    "Orichalcum Mace":                      VespadianItemData("Equipment",        code = 39, classification = ItemClassification.filler,                       ),
    "Orichalcum Scythe":                      VespadianItemData("Equipment",        code = 40, classification = ItemClassification.filler,                       ),
    "Orichalcum Spear":                      VespadianItemData("Equipment",        code = 41, classification = ItemClassification.filler,                       ),
    "Orichalcum Halberd":                      VespadianItemData("Equipment",        code = 42, classification = ItemClassification.filler,                       ),
    "Adamantite Sword":                      VespadianItemData("Strong Equipment",        code = 43, classification = ItemClassification.useful,                       ),
    "Adamantite Longsword":                      VespadianItemData("Strong Equipment",        code = 44, classification = ItemClassification.useful,                       ),
    "Adamantite Battleaxe":                      VespadianItemData("Strong Equipment",        code = 45, classification = ItemClassification.useful,                       ),
    "Adamantite Greataxe":                      VespadianItemData("Strong Equipment",        code = 46, classification = ItemClassification.useful,                       ),
    "Adamantite Warhammer":                      VespadianItemData("Strong Equipment",        code = 47, classification = ItemClassification.useful,                       ),
    "Adamantite Mace":                      VespadianItemData("Strong Equipment",        code = 48, classification = ItemClassification.useful,                       ),
    "Adamantite Scythe":                      VespadianItemData("Strong Equipment",        code = 49, classification = ItemClassification.useful,                       ),
    "Adamantite Spear":                      VespadianItemData("Strong Equipment",        code = 50, classification = ItemClassification.useful,                       ),
    "Adamantite Halberd":                      VespadianItemData("Strong Equipment",        code = 51, classification = ItemClassification.useful,                       ),
    "Defender Sword":                      VespadianItemData("Strong Equipment",        code = 52, classification = ItemClassification.useful,                       ),
    "Magus Staff":                      VespadianItemData("Strong Equipment",        code = 53, classification = ItemClassification.useful,                       ),
    "Archmagus Staff":                      VespadianItemData("Strong Equipment",        code = 54, classification = ItemClassification.useful,                       ),
    "Balmung":                      VespadianItemData("Strong Equipment",        code = 55, classification = ItemClassification.useful,                       ),
    "Death Totem":                      VespadianItemData("Strong Equipment",        code = 56, classification = ItemClassification.useful,                       ),
    "Galactica":                      VespadianItemData("Strong Equipment",        code = 57, classification = ItemClassification.useful,                       ),
    "Memento Mori":                      VespadianItemData("Strong Equipment",        code = 58, classification = ItemClassification.useful,                       ),
    "Steel Dagger":                      VespadianItemData("Equipment",        code = 130, classification = ItemClassification.filler,                       ),
    "Long Knife":                      VespadianItemData("Equipment",        code = 131, classification = ItemClassification.filler,                       ),
    "Vespal Shortsword":                      VespadianItemData("Equipment",        code = 132, classification = ItemClassification.filler,                       ),
    "Cat Claw":                      VespadianItemData("Equipment",        code = 133, classification = ItemClassification.filler,                       ),
    "Cutlass":                      VespadianItemData("Equipment",        code = 134, classification = ItemClassification.filler,                       ),
    "Mythril Dagger":                      VespadianItemData("Equipment",        code = 135, classification = ItemClassification.filler,                       ),
    "Orichalcum Dagger":                      VespadianItemData("Equipment",        code = 136, classification = ItemClassification.filler,                       ),
    "Scimitar":                      VespadianItemData("Equipment",        code = 137, classification = ItemClassification.filler,                       ),
    "Adamantite Dagger":                      VespadianItemData("Strong Equipment",        code = 138, classification = ItemClassification.useful,                       ),
    "Heater Shield":                      VespadianItemData("Equipment",        code = 257, classification = ItemClassification.filler,                       ),
    "Firebolt Wand":                      VespadianItemData("Equipment",        code = 258, classification = ItemClassification.filler,                       ),
    "Kite Shield":                      VespadianItemData("Equipment",        code = 259, classification = ItemClassification.filler,                       ),
    "Round Shield":                      VespadianItemData("Equipment",        code = 260, classification = ItemClassification.filler,                       ),
    "Shortbow":                      VespadianItemData("Equipment",        code = 261, classification = ItemClassification.filler,                       ),
    "Longbow":                      VespadianItemData("Equipment",        code = 262, classification = ItemClassification.filler,                       ),
    "Light Crossbow":                      VespadianItemData("Equipment",        code = 263, classification = ItemClassification.filler,                       ),
    "Heavy Crossbow":                      VespadianItemData("Equipment",        code = 264, classification = ItemClassification.filler,                       ),
    "Buckler":                      VespadianItemData("Equipment",        code = 265, classification = ItemClassification.filler,                       ),
    "Flame Shield":                      VespadianItemData("Equipment",        code = 266, classification = ItemClassification.filler,                       ),
    "Ice Shield":                      VespadianItemData("Equipment",        code = 267, classification = ItemClassification.filler,                       ),
    "Lightning Shield":                      VespadianItemData("Equipment",        code = 268, classification = ItemClassification.filler,                       ),
    "Frostbolt Wand":                      VespadianItemData("Equipment",        code = 269, classification = ItemClassification.filler,                       ),
    "Ligtningbolt Wand":                      VespadianItemData("Equipment",        code = 270, classification = ItemClassification.filler,                       ),
    "Tower Shield":                      VespadianItemData("Equipment",        code = 271, classification = ItemClassification.filler,                       ),
    "Mythril Shield":                      VespadianItemData("Equipment",        code = 272, classification = ItemClassification.filler,                       ),
    "Mythril Tower Shield":                      VespadianItemData("Equipment",        code = 273, classification = ItemClassification.filler,                       ),
    "Lazy Lyre":                      VespadianItemData("Equipment",        code = 274, classification = ItemClassification.filler,                       ),
    "Orichalcum Shield":                      VespadianItemData("Equipment",        code = 275, classification = ItemClassification.filler,                       ),
    "Orichalcum Tower Shield":                      VespadianItemData("Equipment",        code = 276, classification = ItemClassification.filler,                       ),
    "Adamantite Shield":                      VespadianItemData("Strong Equipment",        code = 277, classification = ItemClassification.useful,                       ),
    "Adamantite Tower Shield":                      VespadianItemData("Strong Equipment",        code = 278, classification = ItemClassification.useful,                       ),
    "Gandiva":                      VespadianItemData("Strong Equipment",        code = 279, classification = ItemClassification.useful,                       ),
    "Cosmic Aegis":                      VespadianItemData("Strong Equipment",        code = 280, classification = ItemClassification.useful,                       ),
    "Wizardly Hat":                      VespadianItemData("Equipment",        code = 388, classification = ItemClassification.filler,                       ),
    "Steel Skullcap":                      VespadianItemData("Equipment",        code = 390, classification = ItemClassification.filler,                       ),
    "Steel Helm":                      VespadianItemData("Equipment",        code = 391, classification = ItemClassification.filler,                       ),
    "Greathelm":                      VespadianItemData("Equipment",        code = 392, classification = ItemClassification.filler,                       ),
    "Flame Headscarf":                      VespadianItemData("Equipment",        code = 393, classification = ItemClassification.filler,                       ),
    "Cold Weather Hat":                      VespadianItemData("Equipment",        code = 394, classification = ItemClassification.filler,                       ),
    "Insulated Cap":                      VespadianItemData("Equipment",        code = 395, classification = ItemClassification.filler,                       ),
    "Visor Cap":                      VespadianItemData("Equipment",        code = 396, classification = ItemClassification.filler,                       ),
    "Lifeline Headdress":                      VespadianItemData("Equipment",        code = 397, classification = ItemClassification.filler,                       ),
    "Brain Case":                      VespadianItemData("Equipment",        code = 398, classification = ItemClassification.filler,                       ),
    "Leather Cap":                      VespadianItemData("Equipment",        code = 399, classification = ItemClassification.filler,                       ),
    "Winged Helmet":                      VespadianItemData("Equipment",        code = 400, classification = ItemClassification.filler,                       ),
    "Magus Hat":                      VespadianItemData("Equipment",        code = 401, classification = ItemClassification.filler,                       ),
    "Archmagus Hat":                      VespadianItemData("Strong Equipment",        code = 402, classification = ItemClassification.useful,                       ),
    "Mythril Helm":                      VespadianItemData("Equipment",        code = 403, classification = ItemClassification.filler,                       ),
    "Mythril Greathelm":                      VespadianItemData("Equipment",        code = 404, classification = ItemClassification.filler,                       ),
    "Gold Crown":                      VespadianItemData("Equipment",        code = 405, classification = ItemClassification.filler,                       ),
    "Orichalcum Helm":                      VespadianItemData("Equipment",        code = 406, classification = ItemClassification.filler,                       ),
    "Orichalcum Greathelm":                      VespadianItemData("Equipment",        code = 407, classification = ItemClassification.filler,                       ),
    "Spider Mask":                      VespadianItemData("Equipment",        code = 408, classification = ItemClassification.filler,                       ),
    "Tricorn Hat":                      VespadianItemData("Equipment",        code = 409, classification = ItemClassification.filler,                       ),
    "Shroom Hat":                      VespadianItemData("Equipment",        code = 410, classification = ItemClassification.filler,                       ),
    "Adamantite Helm":                      VespadianItemData("Strong Equipment",        code = 411, classification = ItemClassification.useful,                       ),
    "Adamantite Greathelm":                      VespadianItemData("Strong Equipment",        code = 412, classification = ItemClassification.useful,                       ),
    "Lamia's Crown":                      VespadianItemData("Strong Equipment",        code = 413, classification = ItemClassification.useful,                       ),
    "Mail Shirt":                      VespadianItemData("Equipment",        code = 644, classification = ItemClassification.filler,                       ),
    "Mail Hauberk":                      VespadianItemData("Equipment",        code = 645, classification = ItemClassification.filler,                       ),
    "Scale Armor":                      VespadianItemData("Equipment",        code = 646, classification = ItemClassification.filler,                       ),
    "Partial Plate Armor":                      VespadianItemData("Equipment",        code = 647, classification = ItemClassification.filler,                       ),
    "Full Plate Armor":                      VespadianItemData("Equipment",        code = 648, classification = ItemClassification.filler,                       ),
    "Wizardly Robes":                      VespadianItemData("Equipment",        code = 649, classification = ItemClassification.filler,                       ),
    "Padded Armor":                      VespadianItemData("Equipment",        code = 651, classification = ItemClassification.filler,                       ),
    "Priest Vestments":                      VespadianItemData("Equipment",        code = 652, classification = ItemClassification.filler,                       ),
    "Partial Mythril Armor":                      VespadianItemData("Equipment",        code = 655, classification = ItemClassification.filler,                       ),
    "Full Mythril Armor":                      VespadianItemData("Equipment",        code = 656, classification = ItemClassification.filler,                       ),
    "Leather Armor":                      VespadianItemData("Equipment",        code = 658, classification = ItemClassification.filler,                       ),
    "Brigandine":                      VespadianItemData("Equipment",        code = 659, classification = ItemClassification.filler,                       ),
    "Cloak of Stars":                      VespadianItemData("Equipment",        code = 662, classification = ItemClassification.filler,                       ),
    "Cotton Clothes":                      VespadianItemData("Equipment",        code = 663, classification = ItemClassification.filler,                       ),
    "Magus Robes":                      VespadianItemData("Equipment",        code = 664, classification = ItemClassification.filler,                       ),
    "Archmagus Robes":                      VespadianItemData("Strong Equipment",        code = 665, classification = ItemClassification.useful,                       ),
    "Partial Orichalcum Armor":                      VespadianItemData("Equipment",        code = 666, classification = ItemClassification.filler,                       ),
    "Full Orichalcum Armor":                      VespadianItemData("Equipment",        code = 667, classification = ItemClassification.filler,                       ),
    "Partial Adamantite Armor":                      VespadianItemData("Strong Equipment",        code = 668, classification = ItemClassification.useful,                       ),
    "Full Adamantite Armor":                      VespadianItemData("Strong Equipment",        code = 669, classification = ItemClassification.useful,                       ),
    "Ninja Gi":                      VespadianItemData("Strong Equipment",        code = 670, classification = ItemClassification.useful,                       ),
    "Dark Garb":                      VespadianItemData("Equipment",        code = 671, classification = ItemClassification.filler,                       ),
    "Dragonscale Armor":                      VespadianItemData("Strong Equipment",        code = 672, classification = ItemClassification.useful,                       ),
    "Flame Bracers":                      VespadianItemData("Equipment",        code = 896, classification = ItemClassification.filler,                       ),
    "Frost Bracers":                      VespadianItemData("Equipment",        code = 897, classification = ItemClassification.filler,                       ),
    "Shock Bracers":                      VespadianItemData("Equipment",        code = 898, classification = ItemClassification.filler,                       ),
    "Green Pants":                      VespadianItemData("Equipment",        code = 899, classification = ItemClassification.filler,                       ),
    "Pearl Necklace":                      VespadianItemData("Equipment",        code = 900, classification = ItemClassification.filler,                       ),
    "Haste Bandana":                      VespadianItemData("Equipment",        code = 901, classification = ItemClassification.filler,                       ),
    "Defender Medallion":                      VespadianItemData("Equipment",        code = 902, classification = ItemClassification.filler,                       ),
    "Guardian Medallion":                      VespadianItemData("Equipment",        code = 903, classification = ItemClassification.filler,                       ),
    "Saint's Relic":                      VespadianItemData("Equipment",        code = 904, classification = ItemClassification.filler,                       ),
    "Insomnia Pin":                      VespadianItemData("Equipment",        code = 905, classification = ItemClassification.filler,                       ),
    "Heart Medallion":                      VespadianItemData("Equipment",        code = 906, classification = ItemClassification.filler,                       ),
    "Zoom Scope":                      VespadianItemData("Equipment",        code = 907, classification = ItemClassification.filler,                       ),
    "Star Bracelet":                      VespadianItemData("Equipment",        code = 908, classification = ItemClassification.filler,                       ),
    "Spiked Gauntlet":                      VespadianItemData("Equipment",        code = 909, classification = ItemClassification.filler,                       ),
    "Translucent Cloak":                      VespadianItemData("Equipment",        code = 910, classification = ItemClassification.filler,                       ),
    "Soul Earring":                      VespadianItemData("Equipment",        code = 911, classification = ItemClassification.filler,                       ),
    "Cool Shades":                      VespadianItemData("Equipment",        code = 912, classification = ItemClassification.filler,                       ),
    "Demon Charm":                      VespadianItemData("Equipment",        code = 913, classification = ItemClassification.filler,                       ),
    "Sandals of the Sun":                      VespadianItemData("Strong Equipment",        code = 914, classification = ItemClassification.useful,                       ),
    "Conflagration Ring":                      VespadianItemData("Strong Equipment",        code = 915, classification = ItemClassification.useful,                       ),
    "Sub-Zero Ring":                      VespadianItemData("Strong Equipment",        code = 916, classification = ItemClassification.useful,                       ),
    "Plasma Ring":                      VespadianItemData("Strong Equipment",        code = 917, classification = ItemClassification.useful,                       ),
    "Rush Bandana":                      VespadianItemData("Equipment",        code = 918, classification = ItemClassification.filler,                       ),
    "Frenzy Bandana":                      VespadianItemData("Strong Equipment",        code = 919, classification = ItemClassification.useful,                       ),
    "Fortress Medallion":                      VespadianItemData("Strong Equipment",        code = 920, classification = ItemClassification.useful,                       ),
    "Life Medallion":                      VespadianItemData("Equipment",        code = 921, classification = ItemClassification.filler,                       ),
    "Spirit Earring":                      VespadianItemData("Equipment",        code = 922, classification = ItemClassification.filler,                       ),
    "Power Earring":                      VespadianItemData("Equipment",        code = 923, classification = ItemClassification.useful,                       ),
    "Immortal Medallion":                      VespadianItemData("Strong Equipment",        code = 924, classification = ItemClassification.useful,                       ),
    "Shadow Charm":                      VespadianItemData("Equipment",        code = 925, classification = ItemClassification.filler,                       ),
    "Purifying Talisman":                      VespadianItemData("Equipment",        code = 926, classification = ItemClassification.filler,                       ),
    "Tortoise Shell":                      VespadianItemData("Strong Equipment",        code = 927, classification = ItemClassification.useful,                       ),
    "Antivenom Bracer":                      VespadianItemData("Equipment",        code = 928, classification = ItemClassification.filler,                       ),
    "Heartbinder Ring":                      VespadianItemData("Equipment",        code = 929, classification = ItemClassification.filler,                       ),
    "Silk Sash":                      VespadianItemData("Equipment",        code = 930, classification = ItemClassification.filler,                       ),
    "Healing Tonic": VespadianItemData("Item", code=1152, classification = ItemClassification.filler,),
    "Healing Potion": VespadianItemData("Item", code=1153, classification = ItemClassification.filler,),
    "Healing Solution": VespadianItemData("Item", code=1154, classification = ItemClassification.filler,),
    "Healing Elixer": VespadianItemData("Item", code=1155, classification = ItemClassification.filler,),
    "Ether": VespadianItemData("Item", code=1156, classification = ItemClassification.filler,),
    "Etherium": VespadianItemData("Item", code=1157, classification = ItemClassification.filler,),
    "Etherius": VespadianItemData("Item", code=1158, classification = ItemClassification.filler,),
    "Antidote": VespadianItemData("Item", code=1159, classification = ItemClassification.filler,),
    "Muscle Relaxant": VespadianItemData("Item", code=1160, classification = ItemClassification.filler,),
    "Demineralizer": VespadianItemData("Item", code=1161, classification = ItemClassification.filler,),
    "Eyedrops": VespadianItemData("Item", code=1162, classification = ItemClassification.filler,),
    "Kobold Tooth": VespadianItemData("Item", code=1163, classification = ItemClassification.filler,),
    "Sparkly Stone": VespadianItemData("Item", code=1164, classification = ItemClassification.filler,),
    "Smelling Salts": VespadianItemData("Item", code=1165, classification = ItemClassification.filler,),
    "Slime Ball": VespadianItemData("Item", code=1166, classification = ItemClassification.filler,),
    "Blue Ooze Pearl": VespadianItemData("Item", code=1167, classification = ItemClassification.filler,),
    "Red Ooze Pearl": VespadianItemData("Item", code=1168, classification = ItemClassification.filler,),
    "Green Ooze Pearl": VespadianItemData("Item", code=1169, classification = ItemClassification.filler,),
    "Cerebral Shard": VespadianItemData("Item", code=1170, classification = ItemClassification.filler,),
    "Arachnid Eye": VespadianItemData("Item", code=1171, classification = ItemClassification.filler,),
    "Arachnid Silk": VespadianItemData("Item", code=1172, classification = ItemClassification.filler,),
    "Venom Sample": VespadianItemData("Item", code=1173, classification = ItemClassification.filler,),
    "Ectoplasm": VespadianItemData("Item", code=1174, classification = ItemClassification.filler,),
    "Shadow Vapor": VespadianItemData("Item", code=1175, classification = ItemClassification.filler,),
    "Skull": VespadianItemData("Item", code=1176, classification = ItemClassification.filler,),
    "Square Cut Ruby": VespadianItemData("Item", code=1177, classification = ItemClassification.filler,),
    "Slug Antenna": VespadianItemData("Item", code=1178, classification = ItemClassification.filler,),
    "Steel Ingot": VespadianItemData("Item", code=1179, classification = ItemClassification.filler,),
    "Mythril Ingot": VespadianItemData("Item", code=1180, classification = ItemClassification.filler,),
    "Orichalcum Ingot": VespadianItemData("Item", code=1181, classification = ItemClassification.filler,),
    "Adamantite Ingot": VespadianItemData("Item", code=1182, classification = ItemClassification.filler,),
    "Liquid Fire": VespadianItemData("Item", code=1183, classification = ItemClassification.filler,),
    "Ever Ice": VespadianItemData("Item", code=1184, classification = ItemClassification.filler,),
    "Bottled Lightning": VespadianItemData("Item", code=1185, classification = ItemClassification.filler,),
    "Starshine": VespadianItemData("Item", code=1186, classification = ItemClassification.filler,),
    "Heartstring": VespadianItemData("Item", code=1187, classification = ItemClassification.filler,),
    "Mindpiece": VespadianItemData("Item", code=1188, classification = ItemClassification.filler,),
    "Cotton": VespadianItemData("Item", code=1189, classification = ItemClassification.filler,),
    "Canvas": VespadianItemData("Item", code=1190, classification = ItemClassification.filler,),
    "Silk": VespadianItemData("Item", code=1191, classification = ItemClassification.filler,),
    "Adamant Weave": VespadianItemData("Item", code=1192, classification = ItemClassification.filler,),
    "Dragon Hide": VespadianItemData("Item", code=1193, classification = ItemClassification.filler,),
    "Papyrus Scroll": VespadianItemData("Item", code=1194, classification = ItemClassification.filler,),
    "Canvas Scroll": VespadianItemData("Item", code=1195, classification = ItemClassification.filler,),
    "Silken Scroll": VespadianItemData("Item", code=1196, classification = ItemClassification.filler,),
    "Adamant-Weave scroll": VespadianItemData("Item", code=1197, classification = ItemClassification.filler,),
    "Flame Scroll": VespadianItemData("Item", code=1198, classification = ItemClassification.filler,),
    "Ice Scroll": VespadianItemData("Item", code=1199, classification = ItemClassification.filler,),
    "Lightning Scroll": VespadianItemData("Item", code=1200, classification = ItemClassification.filler,),
    "Opal": VespadianItemData("Item", code=1201, classification = ItemClassification.filler,),
    "Jade": VespadianItemData("Item", code=1202, classification = ItemClassification.filler,),
    "Agate": VespadianItemData("Item", code=1203, classification = ItemClassification.filler,),
    "Moonstone": VespadianItemData("Item", code=1204, classification = ItemClassification.filler,),
    "Quartz": VespadianItemData("Item", code=1205, classification = ItemClassification.filler,),
    "Amethyst": VespadianItemData("Item", code=1206, classification = ItemClassification.filler,),
    "Aquamarine": VespadianItemData("Item", code=1207, classification = ItemClassification.filler,),
    "Garnet": VespadianItemData("Item", code=1208, classification = ItemClassification.filler,),
    "Cat's Eye": VespadianItemData("Item", code=1209, classification = ItemClassification.filler,),
    "Tourmaline": VespadianItemData("Item", code=1210, classification = ItemClassification.filler,),
    "Topaz": VespadianItemData("Item", code=1211, classification = ItemClassification.filler,),
    "Ruby": VespadianItemData("Item", code=1212, classification = ItemClassification.filler,),
    "Sapphire": VespadianItemData("Item", code=1213, classification = ItemClassification.filler,),
    "Emerald": VespadianItemData("Item", code=1214, classification = ItemClassification.filler,),
    "Diamond": VespadianItemData("Item", code=1215, classification = ItemClassification.filler,),
    "Animal Tooth": VespadianItemData("Item", code=1216, classification = ItemClassification.filler,),
    "Awakened Leaf": VespadianItemData("Item", code=1217, classification = ItemClassification.filler,),
    "Arthropod Leg": VespadianItemData("Item", code=1218, classification = ItemClassification.filler,),
    "Mercury Token": VespadianItemData("Key", code=1219, classification = ItemClassification.progression,),
    "Slime Blob": VespadianItemData("Item", code=1220, classification = ItemClassification.filler,),
    "Ogre Spit": VespadianItemData("Item", code=1221, classification = ItemClassification.filler,),
    "Flightless Feather": VespadianItemData("Item", code=1222, classification = ItemClassification.filler,),
    "Fairy Tonic": VespadianItemData("Item", code=1223, classification = ItemClassification.filler,),
    "Dreamworld Sand": VespadianItemData("Item", code=1224, classification = ItemClassification.filler,),
    #"Cold Mist Tome": VespadianItemData("Item", code=1225, classification = ItemClassification.filler,),
    "Strength Boost": VespadianItemData("Item", code=1226, classification = ItemClassification.filler,),
    "Fortitude Boost": VespadianItemData("Item", code=1227, classification = ItemClassification.filler,),
    "Dexterity Boost": VespadianItemData("Item", code=1228, classification = ItemClassification.filler,),
    "Agility Boost": VespadianItemData("Item", code=1229, classification = ItemClassification.filler,),
    "Intellect Boost": VespadianItemData("Item", code=1230, classification = ItemClassification.filler,),
    "Wisdom Boost": VespadianItemData("Item", code=1231, classification = ItemClassification.filler,),
    "Charisma Boost": VespadianItemData("Item", code=1232, classification = ItemClassification.filler,),
    "Spirit Boost": VespadianItemData("Item", code=1233, classification = ItemClassification.filler,),
    "Red Dragon Scale": VespadianItemData("Item", code=1234, classification = ItemClassification.filler,),
    "Blue Dragon Scale": VespadianItemData("Item", code=1235, classification = ItemClassification.filler,),
    "Yellow Dragon Scale": VespadianItemData("Item", code=1236, classification = ItemClassification.filler,),
    "Black Dragon Scale": VespadianItemData("Item", code=1237, classification = ItemClassification.filler,),
    "White Dragon Scale": VespadianItemData("Item", code=1238, classification = ItemClassification.filler,),
    "Green Dragon Scale": VespadianItemData("Item", code=1239, classification = ItemClassification.filler,),
    "Purple Dragon Scale": VespadianItemData("Item", code=1240, classification = ItemClassification.filler,),
    "Plush Mycelium": VespadianItemData("Item", code=1241, classification = ItemClassification.filler,),
    "Red Mushroom": VespadianItemData("Item", code=1242, classification = ItemClassification.filler,),
    "Afterlife Residue": VespadianItemData("Item", code=1243, classification = ItemClassification.filler,),
    "Abyssal Shard": VespadianItemData("Item", code=1244, classification = ItemClassification.filler,),
    "Flame Essence": VespadianItemData("Item", code=1245, classification = ItemClassification.filler,),
    "Ice Essence": VespadianItemData("Item", code=1246, classification = ItemClassification.filler,),
    "Lightning Essence": VespadianItemData("Item", code=1247, classification = ItemClassification.filler,),
    "Life Serum": VespadianItemData("Item", code=1248, classification = ItemClassification.filler,),
    "Flames Tome": VespadianItemData("Tome", code=1249, classification = ItemClassification.filler,),
    "Toxify Tome": VespadianItemData("Tome", code=1250, classification = ItemClassification.filler,),
    "Sleep Tome": VespadianItemData("Tome", code=1251, classification = ItemClassification.filler,),
    "Tremor Tome": VespadianItemData("Tome", code=1252, classification = ItemClassification.filler,),
    "Frostbite Tome": VespadianItemData("Tome", code=1253, classification = ItemClassification.filler,),
    "Shock Tome": VespadianItemData("Tome", code=1254, classification = ItemClassification.filler,),
    "Firestorm Tome": VespadianItemData("Tome", code=1255, classification = ItemClassification.filler,),
    "Slow Tome": VespadianItemData("Tome", code=1256, classification = ItemClassification.filler,),
    "Mass Sleep Tome": VespadianItemData("Tome", code=1257, classification = ItemClassification.filler,),
    "Blizzard Tome": VespadianItemData("Tome", code=1258, classification = ItemClassification.filler,),
    "Lightning Bolt Tome": VespadianItemData("Tome", code=1259, classification = ItemClassification.filler,),
    "Hasten Tome": VespadianItemData("Tome", code=1260, classification = ItemClassification.filler,),
    "Shark Tooth": VespadianItemData("Item", code=1261, classification = ItemClassification.filler,),
    "Desert Pearl": VespadianItemData("Item", code=1262, classification = ItemClassification.filler,),
    "Construct Core": VespadianItemData("Item", code=1263, classification = ItemClassification.filler,),
    "Gelatin Cube": VespadianItemData("Item", code=1264, classification = ItemClassification.filler,),
    "Greeting Card": VespadianItemData("Item", code=1265, classification = ItemClassification.filler,),
    "Death Tome": VespadianItemData("Tome", code=1266, classification = ItemClassification.filler,),
    "Paralyze Tome": VespadianItemData("Tome", code=1267, classification = ItemClassification.filler,),
    "Sharpen Tome": VespadianItemData("Tome", code=1268, classification = ItemClassification.filler,),
    "Dinosaur Bone": VespadianItemData("Item", code=1269, classification = ItemClassification.filler,),
    "Golden Feather": VespadianItemData("Item", code=1270, classification = ItemClassification.filler,),
    "Mars Token": VespadianItemData("Key", code=1271, classification = ItemClassification.progression,),
    "Sun Shard": VespadianItemData("Item", code=1272, classification = ItemClassification.filler,),
    "Awakened Branch": VespadianItemData("Item", code=1273, classification = ItemClassification.filler,),
    "Great Construct Core": VespadianItemData("Item", code=1274, classification = ItemClassification.filler,),
    "Inferno Tome": VespadianItemData("Tome", code=1275, classification = ItemClassification.filler,),
    "Teleport Tome": VespadianItemData("Tome", code=1276, classification = ItemClassification.filler,),
    "Toxic Cloud Tome": VespadianItemData("Tome", code=1277, classification = ItemClassification.filler,),
    "Hex Breaker": VespadianItemData("Item", code=1278, classification = ItemClassification.filler,),
    #"Dynamite": VespadianItemData("Item", code=1279, classification = ItemClassification.filler,),
    "Squid Ink": VespadianItemData("Item", code=1280, classification = ItemClassification.filler,),
    "Yellow Ooze Pearl": VespadianItemData("Item", code=1281, classification = ItemClassification.filler,),   
    "Absolute Zero Tome": VespadianItemData("Tome", code=1282, classification = ItemClassification.filler,),  
    "Plasma Storm Tome": VespadianItemData("Tome", code=1283, classification = ItemClassification.filler,),   
    "Dispel Tome": VespadianItemData("Tome", code=1284, classification = ItemClassification.filler,),
    "Earthquake Tome": VespadianItemData("Tome", code=1285, classification = ItemClassification.filler,),     
    "Mass Paralyze Tome": VespadianItemData("Tome", code=1286, classification = ItemClassification.filler,),  
    "Mass Teleport Tome": VespadianItemData("Strong Tome", code=1287, classification = ItemClassification.useful,),  
    "Mass Extinction Tome": VespadianItemData("Tome", code=1288, classification = ItemClassification.filler,),
    "Meteor Tome": VespadianItemData("Strong Tome", code=1289, classification = ItemClassification.useful,),
    "Distaster Tome": VespadianItemData("Strong Tome", code=1290, classification = ItemClassification.useful,),      
    "Wind Crystal": VespadianItemData("Item", code=1291, classification = ItemClassification.filler,),        
    "Saturn Token": VespadianItemData("Key", code=1292, classification = ItemClassification.progression,),        
    "Poison Pearl": VespadianItemData("Item", code=1293, classification = ItemClassification.filler,),        
    "Sea Scale": VespadianItemData("Item", code=1294, classification = ItemClassification.filler,),
    "Water Crystal": VespadianItemData("Item", code=1295, classification = ItemClassification.filler,),       
    "Rainbow Ooze Pearl": VespadianItemData("Item", code=1296, classification = ItemClassification.filler,),  
    "Jupiter Token": VespadianItemData("Key", code=1297, classification = ItemClassification.progression,),       
    "Venus Token": VespadianItemData("Key", code=1298, classification = ItemClassification.progression,),
    #"Percy's Notebook": VespadianItemData("Key", code=1408, classification = ItemClassification.progression,),
    "Ariadne": VespadianItemData("Key", code=1409, classification = ItemClassification.progression,),
    #"Thorn of Benelohim": VespadianItemData("Key", code=1410, classification = ItemClassification.progression,),
    #"Treasure Stash Key": VespadianItemData("Key", code=1411, classification = ItemClassification.progression,),
    #"Archive Key": VespadianItemData("Key", code=1412, classification = ItemClassification.progression,),
    #"Lock Picking Kit": VespadianItemData("Key", code=1413, classification = ItemClassification.progression,),
    #"Mark of the Magi": VespadianItemData("Key", code=1414, classification = ItemClassification.progression,),
    "Tunnel Key": VespadianItemData("Key", code=1415, classification = ItemClassification.progression,),
    "Waxing Crescent": VespadianItemData("Key", code=1416, classification = ItemClassification.progression,),
    #"Room Key": VespadianItemData("Key", code=1417, classification = ItemClassification.progression,),
    "Mole Key": VespadianItemData("Key", code=1418, classification = ItemClassification.progression,),
    "Fortress Key": VespadianItemData("Key", code=1419, classification = ItemClassification.progression,),
    "Silver Key": VespadianItemData("Key", code=1420, classification = ItemClassification.progression,),
    "Intermediate Blueprints": VespadianItemData("Key", code=1421, classification = ItemClassification.useful,),
    "Advanced Blueprints": VespadianItemData("Key", code=1422, classification = ItemClassification.useful,),
    "Palace Key": VespadianItemData("Key", code=1423, classification = ItemClassification.progression,),
    "Nitro Powder": VespadianItemData("Key", code=1424, classification = ItemClassification.progression,),
    "Master Blueprints": VespadianItemData("Key", code=1425, classification = ItemClassification.useful,),
    "Waterfall Key": VespadianItemData("Key", code=1426, classification = ItemClassification.progression,),
    "Waning Gibbous": VespadianItemData("Key", code=1427, classification = ItemClassification.progression,),
    "Gold Key": VespadianItemData("Key", code=1428, classification = ItemClassification.progression,),
    "Adventuring License": VespadianItemData("Key", code=1429, classification = ItemClassification.progression,),
    "Magic Mirror": VespadianItemData("Key", code=1430, classification = ItemClassification.progression,),
}

event_item_table: Dict[str, VespadianItemData] = {}

#Make item categories
item_name_groups: Dict[str, Set[str]] = {}
for item in item_table.keys():
    category = item_table[item].category
    if category not in item_name_groups.keys():
        item_name_groups[category] = set()
    item_name_groups[category].add(item)