from typing import Dict, List, NamedTuple, Optional

from BaseClasses import MultiWorld, Region, Entrance
from .Locations import VespadianLocation, location_table

class VespadianRegionData(NamedTuple):
    locations: List[str]
    region_exits: Optional[List[str]]

def create_regions(multiworld: MultiWorld, player: int, options):
    regions: Dict[str, VespadianRegionData] = {
        "Menu": VespadianRegionData([], ["Menendel Underground, Moonlit Shrine, Mole Hole, First Continent"]),
        "Menendel Underground": VespadianRegionData([], []),
        "Moonlit Shrine": VespadianRegionData([], []),
        "Mole Hole": VespadianRegionData([], []),
        "First Continent": VespadianRegionData([], ["Hearthaven", "Island Fortress", "Farsight", "Bottomless Hole"]),
        "Hearthaven": VespadianRegionData([], []),
        "Island Fortress": VespadianRegionData([], []),
        "Farsight": VespadianRegionData([], []),
        "Bottomless Hole": VespadianRegionData([], ["The Great Between"]),
        "The Great Between": VespadianRegionData([], ["Second Continent"]),
        "Second Continent": VespadianRegionData([], ["Arva Mandia", "Ancient Catacombs", "Desert Palace", "Wide World"]),
        "Arva Mandia": VespadianRegionData([], []),
        "Ancient Catacombs": VespadianRegionData([], []),
        "Desert Palace": VespadianRegionData([], []),
        "Wide World": VespadianRegionData([], ["Hideaway", "Secret Underpass", "Waterfall Temple", "Starcrossed Citadel 1", "Astrological Observatory"]),
        "Hideaway": VespadianRegionData([], []),
        "Secret Underpass": VespadianRegionData([], []),
        "Waterfall Temple": VespadianRegionData([], []),
        "Starcrossed Citadel 1": VespadianRegionData([], ["Starcrossed Citadel 2"]),
        "Starcrossed Citadel 2": VespadianRegionData([], ["Starcrossed Citadel 3"]),
        "Starcrossed Citadel 3": VespadianRegionData([], []),
        "Astrological Observatory": VespadianRegionData([], [])
    }

    regions["Menendel Underground"].locations.append("Menendel Underground Corridors Chest 1")
    regions["Menendel Underground"].locations.append("Menendel Underground Corridors Chest 2")
    regions["Menendel Underground"].locations.append("Menendel Underground Corridors Chest 3")
    regions["Menendel Underground"].locations.append("Menendel Underground Corridors Chest 4")
    regions["Menendel Underground"].locations.append("Menendel Underground Corridors Key Chest")
    regions["Menendel Underground"].locations.append("Menendel Underground East Tunnel Chest 1")
    regions["Menendel Underground"].locations.append("Menendel Underground East Tunnel Chest 2")
    regions["Menendel Underground"].locations.append("Menendel Underground East Tunnel Chest 3")
    regions["Menendel Underground"].locations.append("Menendel Underground East Tunnel Chest 4")
    regions["Menendel Underground"].locations.append("Menendel Underground West Tunnel Chest 1")
    regions["Menendel Underground"].locations.append("Menendel Underground West Tunnel Chest 2")
    regions["Menendel Underground"].locations.append("Menendel Underground Vault Chest 1")
    regions["Menendel Underground"].locations.append("Menendel Underground Vault Chest 2")
    regions["Menendel Underground"].locations.append("Menendel Underground Vault Chest 3")
    regions["Menendel Underground"].locations.append("Menendel Underground Vault Chest 4")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Antechamber Chest 1")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Antechamber Chest 2")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Antechamber Chest 3")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Antechamber Chest 4")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Antechamber Chest 5")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Antechamber Chest 6")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Antechamber Chest 7")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Antechamber Chest 8")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Antechamber Chest 9")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Antechamber Chest 10")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Mount Chest 1")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Mount Chest 2")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Mount Chest 3")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Mount Chest 4")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Mount Chest 5")
    regions["Moonlit Shrine"].locations.append("Moonlit Shrine Mount Chest 6")
    regions["Mole Hole"].locations.append("Mole Hole Ground Level Chest 1")
    regions["Mole Hole"].locations.append("Mole Hole Ground Level Chest 2")
    regions["Mole Hole"].locations.append("Mole Hole Ground Level Chest 3")
    regions["Mole Hole"].locations.append("Mole Hole Ground Level Chest 4")
    regions["Mole Hole"].locations.append("Mole Hole Ground Level Chest 5")
    regions["Mole Hole"].locations.append("Mole Hole Ground Depths Key Chest")
    regions["Mole Hole"].locations.append("Mole Hole Ground Depths Chest 1")
    regions["Mole Hole"].locations.append("Rescue Ariadne")
    regions["Hearthaven"].locations.append("Hearthaven South Chest")
    regions["Hearthaven"].locations.append("Hearthaven North Chest 1")
    regions["Hearthaven"].locations.append("Hearthaven North Chest 2")
    regions["Hearthaven"].locations.append("Hearthaven Crafting Shop Chest")
    regions["Hearthaven"].locations.append("Hearthaven Library Chest")
    regions["Hearthaven"].locations.append("Gift From Maria")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 1")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 2")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 3")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 4")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 5")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 6")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 7")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 8")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 9")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 10")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 11")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 12")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 13")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 14")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 15")
    regions["Island Fortress"].locations.append("Island Fortress Keep Chest 16")
    regions["Island Fortress"].locations.append("Island Fortress Basement Chest 1")
    regions["Island Fortress"].locations.append("Island Fortress Basement Chest 2")
    regions["Island Fortress"].locations.append("Island Fortress Basement Chest 3")
    regions["Island Fortress"].locations.append("Island Fortress Hallway Silver Key Chest")
    regions["Island Fortress"].locations.append("Island Fortress Towers Chest 1")
    regions["Island Fortress"].locations.append("Island Fortress Towers Chest 2")
    regions["Island Fortress"].locations.append("Island Fortress Towers Chest 3")
    regions["Island Fortress"].locations.append("Island Fortress Towers Chest 4")
    regions["Farsight"].locations.append("Farsight Inn Chest 1")
    regions["Farsight"].locations.append("Farsight Inn Chest 2")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B1 Chest")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B3 Chest 1")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B3 Chest 2")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B3 Chest 3")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B3 Chest 4")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B3 Chest 5")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B3 Chest 6")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B4 Chest 1")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B4 Chest 2")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B4 Chest 3")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B4 Chest 4")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B4 Chest 5")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B4 Chest 6")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B4 Chest 7")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B5 Chest 1")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B5 Chest 2")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B5 Chest 3")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B5 Chest 4")
    regions["Bottomless Hole"].locations.append("Bottomless Hole B5 Chest 5")
    regions["The Great Between"].locations.append("The Great Between: Web of Worlds Chest 1")
    regions["The Great Between"].locations.append("The Great Between: Web of Worlds Chest 2")
    regions["The Great Between"].locations.append("The Great Between: Web of Worlds Chest 3")
    regions["The Great Between"].locations.append("The Great Between: Web of Worlds Chest 4")
    regions["The Great Between"].locations.append("The Great Between: Isles of Thought Chest 1")
    regions["The Great Between"].locations.append("The Great Between: Isles of Thought Chest 2")
    regions["The Great Between"].locations.append("The Great Between: Isles of Thought Chest 3")
    regions["The Great Between"].locations.append("Bottomless Hole Bottom Chest 1")
    regions["The Great Between"].locations.append("Bottomless Hole Bottom Chest 2")
    regions["The Great Between"].locations.append("Bottomless Hole Bottom Chest 3")
    regions["Arva Mandia"].locations.append("Arva Mandia General Store Chest")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs East Tunnel Chest 1")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs East Tunnel Chest 2")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Cistern Chest 1")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Cistern Chest 2")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Cistern Chest 3")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Cistern Chest 4")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Cistern Chest 5")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Cistern Chest 6")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Cistern Chest 7")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Cistern Chest 8")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Cistern Chest 9")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Cistern Chest 10")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs North Tunnel Chest 1")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs North Tunnel Chest 2")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs North Tunnel Chest 3")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs North Tunnel Chest 4")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Artery Chest 1")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Artery Chest 2")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Artery Chest 3")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Artery Chest 4")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Artery Chest 5")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Artery Chest 6")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Artery Chest 7")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Treasury Chest")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Antechamber Chest 1")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Antechamber Chest 2")
    regions["Ancient Catacombs"].locations.append("Ancient Catacombs Antechamber Chest 3")
    regions["Desert Palace"].locations.append("Desert Palace Hall Chest 1")
    regions["Desert Palace"].locations.append("Desert Palace Hall Chest 2")
    regions["Desert Palace"].locations.append("Desert Palace Hall Chest 3")
    regions["Desert Palace"].locations.append("Desert Palace Hall Chest 4")
    regions["Desert Palace"].locations.append("Desert Palace West Wing Chest 1")
    regions["Desert Palace"].locations.append("Desert Palace West Wing Chest 2")
    regions["Desert Palace"].locations.append("Desert Palace Sitting Room Chest")
    regions["Desert Palace"].locations.append("Desert Palace North Chamber Chest 1")
    regions["Desert Palace"].locations.append("Desert Palace North Chamber Chest 2")
    regions["Desert Palace"].locations.append("Desert Palace North Chamber Chest 3")
    regions["Desert Palace"].locations.append("Desert Palace North Chamber Chest 4")
    regions["Desert Palace"].locations.append("Desert Palace South Chamber Chest 1")
    regions["Desert Palace"].locations.append("Desert Palace South Chamber Chest 2")
    regions["Desert Palace"].locations.append("Desert Palace South Chamber Chest 3")
    regions["Desert Palace"].locations.append("Desert Palace South Chamber Chest 4")
    regions["Desert Palace"].locations.append("Desert Palace Audience Chamber Chest")
    regions["Hideaway"].locations.append("Hideaway General Store Chest")
    regions["Hideaway"].locations.append("Hideaway: Victoria's House Chest")
    regions["Secret Underpass"].locations.append("Secret Underpass Atrium Chest 1")
    regions["Secret Underpass"].locations.append("Secret Underpass Atrium Chest 2")
    regions["Secret Underpass"].locations.append("Secret Underpass Atrium Chest 3")
    regions["Secret Underpass"].locations.append("Secret Underpass Atrium Chest 4")
    regions["Secret Underpass"].locations.append("Secret Underpass Atrium Chest 5")
    regions["Secret Underpass"].locations.append("Secret Underpass Atrium Chest 6")
    regions["Secret Underpass"].locations.append("Secret Underpass Atrium Chest 7")
    regions["Secret Underpass"].locations.append("Secret Underpass Corridors Chest 1")
    regions["Secret Underpass"].locations.append("Secret Underpass Corridors Chest 2")
    regions["Secret Underpass"].locations.append("Secret Underpass Corridors Chest 3")
    regions["Secret Underpass"].locations.append("Secret Underpass Corridors Chest 4")
    regions["Secret Underpass"].locations.append("Secret Underpass Corridors Chest 5")
    regions["Secret Underpass"].locations.append("Secret Underpass Tunnel Chest")
    regions["Secret Underpass"].locations.append("Secret Grove Chest")
    regions["Waterfall Temple"].locations.append("Waterfall Temple East Wing Chest")
    regions["Waterfall Temple"].locations.append("Waterfall Temple East Sanctum Chest")
    regions["Waterfall Temple"].locations.append("Waterfall Temple North Court Chest")
    regions["Waterfall Temple"].locations.append("Waterfall Temple Waterway Chest 1")
    regions["Waterfall Temple"].locations.append("Waterfall Temple Waterway Chest 2")
    regions["Waterfall Temple"].locations.append("Waterfall Temple Waterway Chest 3")
    regions["Waterfall Temple"].locations.append("Waterfall Temple Waterway Chest 4")
    regions["Waterfall Temple"].locations.append("Waterfall Temple Altar Chest")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Outer Wall Chest 1")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Outer Wall Chest 2")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Outer Wall Chest 3")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Outer Wall Chest 4")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Outer Wall Chest 5")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Outer Wall Chest 6")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Outer Wall Chest 7")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Outer Wall Chest 8")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Outer Wall Chest 9")
    regions["Starcrossed Citadel 3"].locations.append("Starcrossed Citadel Outer Wall Chest 10")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Stronghold Chest 1")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Stronghold Chest 2")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Stronghold Chest 3")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Chapel Chest 1")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Chapel Chest 2")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Chapel Chest 3")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Chapel Chest 4")
    regions["Starcrossed Citadel 1"].locations.append("Starcrossed Citadel Chapel Chest 5")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel North Chamber Chest 1")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel North Chamber Chest 2")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel North Chamber Chest 3")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Labyrinth Chest 1")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Labyrinth Chest 2")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Garden Chest")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Second Floor Hallway Chest")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Conservatory Chest")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Living Quarters Chest 1")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Living Quarters Chest 2")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Living Quarters Chest 3")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Living Quarters Chest 4")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Living Quarters Chest 5")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Living Quarters Chest 6")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Crypt Chest 1")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Crypt Chest 2")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Crypt Chest 3")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Crypt Chest 4")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Cavern Chest 1")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Cavern Chest 2")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Cavern Chest 3")
    regions["Starcrossed Citadel 2"].locations.append("Starcrossed Citadel Cavern Chest 4")
    regions["Starcrossed Citadel 3"].locations.append("Starcrossed Citadel Chamber of Fire Chest 1")
    regions["Starcrossed Citadel 3"].locations.append("Starcrossed Citadel Chamber of Fire Chest 2")
    regions["Astrological Observatory"].locations.append("Astrological Observatory Chest 1")
    regions["Astrological Observatory"].locations.append("Astrological Observatory Chest 2")

    # Set up the regions correctly.
    for name, data in regions.items():
        multiworld.regions.append(create_region(multiworld, player, name, data))

def connect_entrances(multiworld: MultiWorld, player: int):
    multiworld.get_entrance("Menendel Underground", player).connect(multiworld.get_region("Menendel Underground", player))
    multiworld.get_entrance("Moonlit Shrine", player).connect(multiworld.get_region("Moonlit Shrine", player))
    multiworld.get_entrance("Mole Hole", player).connect(multiworld.get_region("Mole Hole", player))
    multiworld.get_entrance("First Continent", player).connect(multiworld.get_region("First Continent", player))
    multiworld.get_entrance("Hearthaven", player).connect(multiworld.get_region("Hearthaven", player))
    multiworld.get_entrance("Island Fortress", player).connect(multiworld.get_region("Island Fortress", player))
    multiworld.get_entrance("Farsight", player).connect(multiworld.get_region("Farsight", player))
    multiworld.get_entrance("Bottomless Hole", player).connect(multiworld.get_region("Bottomless Hole", player))
    multiworld.get_entrance("The Great Between", player).connect(multiworld.get_region("The Great Between", player))
    multiworld.get_entrance("Second Continent", player).connect(multiworld.get_region("Second Continent", player))
    multiworld.get_entrance("Arva Mandia", player).connect(multiworld.get_region("Arva Mandia", player))
    multiworld.get_entrance("Ancient Catacombs", player).connect(multiworld.get_region("Ancient Catacombs", player))
    multiworld.get_entrance("Desert Palace", player).connect(multiworld.get_region("Desert Palace", player))
    multiworld.get_entrance("Second Continent", player).connect(multiworld.get_region("Second Continent", player))
    multiworld.get_entrance("Hideaway", player).connect(multiworld.get_region("Hideaway", player))
    multiworld.get_entrance("Secret Underpass", player).connect(multiworld.get_region("Secret Underpass", player))
    multiworld.get_entrance("Waterfall Temple", player).connect(multiworld.get_region("Waterfall Temple", player))
    multiworld.get_entrance("Starcrossed Citadel 1", player).connect(multiworld.get_region("Starcrossed Citadel 1", player))
    multiworld.get_entrance("Starcrossed Citadel 2", player).connect(multiworld.get_region("Starcrossed Citadel 2", player))
    multiworld.get_entrance("Starcrossed Citadel 3", player).connect(multiworld.get_region("Starcrossed Citadel 3", player))
    multiworld.get_entrance("Astrological Observatory", player).connect(multiworld.get_region("Astrological Observatory", player))

def create_region(multiworld: MultiWorld, player: int, name: str, data: VespadianRegionData):
    region = Region(name, player, multiworld)
    if data.locations:
        for loc_name in data.locations:
            loc_data = location_table.get(loc_name)
            location = VespadianLocation(player, loc_name, loc_data.code if loc_data else None, region)
            region.locations.append(location)

    if data.region_exits:
        for exit in data.region_exits:
            entrance = Entrance(player, exit, region)
            region.exits.append(entrance)

    return region